### ISSUE TITLE
app cannot run at ch02-05-transitions

### ISSUE THREAD

**Issue by SHERlocked93** [dogriffiths/ReactCookbook-source#105]
When I download `ch02-05-transitions` and run `yarn install`, it told me that something went wrong

![](https://user-images.githubusercontent.com/24636076/149087913-8cccb072-98fc-43ec-acba-d8a0fe107b48.png)

I added the file `.env` as prompted and it worked. Please consider if you need to make some changes in the repository, to help those who might be running wrong?

**Comment by dogriffiths** [comment]
Hello,

Apologies for the delay in responding; it's been a busy week :) This sort of problem usually occurs because some library is asking for a version of the babel loader that conflicts with the one built-in to CRA. It's sadly quite common (the last time I looked, Storybook was causing the same issues with various versions of CRA). The SKIP_PREFLIGHT_CHECK will work, but it does potentially leave your project open to bugs. That's because the application might end up using the wrong version of a library. It will *probably* be OK, but it's best to avoid it if possible. 

It can be worth trying to fix the dependency tree using the steps they suggest.

DG
